### ISSUE TITLE
Checkpoint included in repo

### ISSUE THREAD

**Issue by mirisr** [akosiorek/sqair#3]
The notebook says, "The only checkpoint that comes with the github repo is 1000000 or int(1e6)". I don't believe this is true at the moment. Is it not suppose to be located at "sqair/release_models/mnist_mlp/1/". The only file there is the flags.json. When downloading the other checkpoints, 1e6 is missing from the download.

**Comment by akosiorek** [comment]
I've updated the notebook description as I currently have no access to the 1e6 checkpoint. Thanks for pointing this out.
